# Generated by Django 6.0.5 on 2026-05-10 02:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("page_start", models.PositiveIntegerField(default=1)),
                ("page_end", models.PositiveIntegerField(default=1)),
                ("content", models.TextField(blank=True)),
                ("char_count", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["textbook_id", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decision_id", models.CharField(max_length=255, unique=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("merge", "Merge"),
                            ("keep", "Keep"),
                            ("remove", "Remove"),
                        ],
                        max_length=20,
                    ),
                ),
                ("affected_node_ids", models.JSONField(blank=True, default=list)),
                ("reason", models.TextField(blank=True)),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("teacher_overridden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "decision_id"],
            },
        ),
        migrations.CreateModel(
            name="Textbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("original_name", models.CharField(max_length=255)),
                ("file", models.FileField(blank=True, upload_to="textbooks/")),
                ("file_format", models.CharField(max_length=32)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("total_pages", models.PositiveIntegerField(default=0)),
                ("total_chars", models.PositiveIntegerField(default=0)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsing", "Parsing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "processing_mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("quality", "Quality")],
                        default="demo",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_messages",
                        to="textbooks.integrationdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("definition", models.TextField(blank=True)),
                ("category", models.CharField(default="核心概念", max_length=255)),
                ("page", models.PositiveIntegerField(default=1)),
                ("frequency", models.PositiveIntegerField(default=1)),
                ("source_node_ids", models.JSONField(blank=True, default=list)),
                ("is_integrated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_nodes",
                        to="textbooks.chapter",
                    ),
                ),
                (
                    "textbook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_nodes",
                        to="textbooks.textbook",
                    ),
                ),
            ],
            options={
                "ordering": ["node_id"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("prerequisite", "Prerequisite"),
                            ("parallel", "Parallel"),
                            ("contains", "Contains"),
                            ("applies_to", "Applies To"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="textbooks.knowledgenode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="textbooks.knowledgenode",
                    ),
                ),
            ],
            options={
                "ordering": ["source_id", "target_id", "id"],
            },
        ),
        migrations.AddField(
            model_name="integrationdecision",
            name="result_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="integration_decisions",
                to="textbooks.knowledgenode",
            ),
        ),
        migrations.CreateModel(
            name="RagChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_id", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("page_start", models.PositiveIntegerField(default=1)),
                ("page_end", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=0)),
                ("vector", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rag_chunks",
                        to="textbooks.chapter",
                    ),
                ),
                (
                    "textbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_chunks",
                        to="textbooks.textbook",
                    ),
                ),
            ],
            options={
                "ordering": ["textbook_id", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("quality", "Quality")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_stage", models.CharField(default="pending", max_length=255)),
                ("progress", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "textbooks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pipeline_runs",
                        to="textbooks.textbook",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="textbook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="textbooks.textbook",
            ),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("textbook", "chapter_id"), name="unique_textbook_chapter_id"
            ),
        ),
    ]
